baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jacob R. Stevens"
theme = "hugo-theme-cactus"

[params]
  # Site description
  description = "Jacob R. Stevens's writings, notes, etc."
  
  # Author information
  author = "Jacob R. Stevens"
  
  # Social links
  github = "JakeStevens"
  twitter = "_JacobRStevens_"
  linkedin = "yourusername"
  
  # Theme customization
  showThemeNotice = true
  showPostsSummary = true
  
  # Color palette options: "default", "light", "dark"
  palette = "default"
  
  # Math rendering (set to true if you need LaTeX math)
  math = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 30